# Generated by Django 5.0 on 2024-02-09 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='projects',
        ),
    ]
