# Generated by Django 5.0 on 2024-02-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_tasks_status'),
        ('teams', '0002_remove_teams_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='teams', to='project.project'),
        ),
    ]
