# Generated by Django 5.0 on 2024-02-10 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_usernetwork'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserNetwork',
        ),
    ]
