# Generated by Django 5.0 on 2024-02-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chat_messages_chat_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='image',
            field=models.ImageField(default='default_chat.png', upload_to='chat_images'),
        ),
    ]
