# Generated by Django 5.0 on 2024-02-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_rename_message_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
