# Generated by Django 5.0 on 2024-02-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_chat_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='chat',
            field=models.ManyToManyField(related_name='messages_related', to='chat.chat'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='messages',
            field=models.ManyToManyField(related_name='chat_related', to='chat.chatmessage'),
        ),
    ]
