# Generated by Django 5.0 on 2024-02-01 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
