# Generated by Django 5.0 on 2024-02-10 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_project_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='assigned_users',
        ),
    ]
